const { PrismaClient } = require('@prisma/client');
const p = new PrismaClient();

const faqs = [
  // EMI Calculator
  { calculatorId: 'emi', sortOrder: 0, question: 'Home Loan EMI formula kya hota hai?', answer: 'EMI = P x r x (1+r)^n / ((1+r)^n - 1). Yahan P = Loan Amount, r = Monthly Interest Rate (Annual Rate / 12 / 100), n = Tenure in months. Yeh formula exact EMI calculate karta hai jo aapko har mahine bank ko deni hogi.' },
  { calculatorId: 'emi', sortOrder: 1, question: 'Kya main apni EMI kam kar sakta hoon?', answer: '3 tarike hain: (1) Loan tenure badhao — longer tenure se EMI ghatti hai lekin total interest zyada hota hai. (2) Balance Transfer karake lower interest rate lao. (3) Lump sum prepayment karo taaki outstanding principal ghate aur accordingly EMI ya tenure adjust ho.' },
  { calculatorId: 'emi', sortOrder: 2, question: 'EMI income ka kitna percent honi chahiye?', answer: 'Financial experts recommend karte hain ki aapki total EMIs (home loan + car + personal sab milake) aapki net monthly income ke 40-50% se zyada na hon. Isse FOIR (Fixed Obligation to Income Ratio) kehte hain. 40% se kam FOIR = best loan rates.' },
  { calculatorId: 'emi', sortOrder: 3, question: 'Kya Home Loan EMI par tax benefit milta hai?', answer: 'Haan! EMI ke 2 parts hain — Principal aur Interest. Principal repayment par Section 80C (max Rs 1.5 Lakh/year) aur Interest payment par Section 24(b) (max Rs 2 Lakh/year for self-occupied property) ka tax benefit milta hai, effectively loan cost significantly ghatta hai.' },
  { calculatorId: 'emi', sortOrder: 4, question: 'Floating aur Fixed rate me se kaun better hai?', answer: 'Floating Rate (RBI repo rate se linked) usually 0.5-1.5% lower hoti hai aur long-term me koi foreclosure charge nahi hota. Fixed Rate certainty deta hai lekin higher cost aata hai. RBI rate cut cycle mein floating rate zyada faydemand hoti hai — abhi ke maahol mein floating recommend hai.' },
  { calculatorId: 'emi', sortOrder: 5, question: 'EMI miss hone par kya hoga?', answer: 'Ek EMI miss hone par bank late payment charges (Rs 500-2000) lagate hain aur CIBIL score 50-100 points ghatta hai. 3 se zyada consecutive EMIs miss hone par account NPA declare ho sakta hai, jo next 7 saal tak credit record kharab karta hai aur future loans/credit cards block ho sakte hain.' },

  // Loan Eligibility
  { calculatorId: 'eligibility', sortOrder: 0, question: 'Loan eligibility kaise calculate hoti hai?', answer: 'Bank aapki net monthly income ka 40-50% FOIR limit use karte hain. Agar income Rs 50,000/month hai aur existing EMIs Rs 10,000 hain, toh eligible new EMI = Rs 15,000-20,000. Is EMI se reverse calculation karke maximum loan amount nikalte hain based on current rate aur tenure.' },
  { calculatorId: 'eligibility', sortOrder: 1, question: 'CIBIL score kitna hona chahiye home loan ke liye?', answer: '750+ CIBIL score ideal hai — isme lowest possible rates milti hain. 700-749 par loan milta hai lekin slightly higher rate par. 650-699 par kuch NBFCs consider karte hain. 650 se kam par standard bank home loan extremely difficult hai. BFS 650+ wale cases bhi specialized channels se handle karta hai.' },
  { calculatorId: 'eligibility', sortOrder: 2, question: 'Kya self-employed ko home loan milna mushkil hai?', answer: 'Nahi, lekin process alag hai. Self-employed ko 2-3 saal ke ITR, GST returns, aur audited balance sheets deni hoti hain. BFS self-employed clients ke liye specialized banking channels use karta hai jo business income ko properly evaluate karte hain — ek business owner ko salaried equivalent maan ke process karte hain.' },
  { calculatorId: 'eligibility', sortOrder: 3, question: 'Co-applicant add karne se eligibility badhti hai kya?', answer: 'Haan, significantly badhti hai. Agar aap earning spouse ya parents ko co-applicant banate hain, dono ki combined income se eligibility calculate hoti hai — sometimes 50-80% zyada loan amount milti hai. Co-applicant ka bhi achha CIBIL score (700+) hona zaroori hai nahi toh fayda nahi hoga.' },
  { calculatorId: 'eligibility', sortOrder: 4, question: 'Age ka loan eligibility par kya impact hota hai?', answer: 'Bank generally 60-65 years (retirement age) tak ka tenure dete hain. Agar aap 45 saal ke hain, maximum tenure 15-20 saal hoga vs 30 saal for a 30-year-old. Shorter tenure = higher EMI = lower eligibility for same loan amount. Isliye jitna jaldi loan lo, tenure utna zyada milega.' },
  { calculatorId: 'eligibility', sortOrder: 5, question: 'Existing loans se eligibility kitni kam hoti hai?', answer: 'Har existing EMI directly new loan eligibility ghata deta hai. Example: Rs 60,000 income, Rs 20,000 existing car loan EMI. Bank eligible new EMI = 50% of 60,000 - 20,000 = Rs 10,000. Is Rs 10,000 EMI se Rs 7-8 Lakh home loan hi milega at 9% for 20 years. Existing loans close karo to maximize eligibility.' },

  // Balance Transfer
  { calculatorId: 'balance-transfer', sortOrder: 0, question: 'Balance Transfer se actually kitni savings hoti hai?', answer: 'Example: Rs 50 Lakh loan, 15 saal baki, current rate 9.5%, new rate 8.5%. Monthly EMI saving approximately Rs 3,200. Total 15 saal savings approximately Rs 5.76 Lakh — minus processing fee (approx Rs 15,000-25,000). Net savings approximately Rs 5.5 Lakh. Balance Transfer ek baar ka kaam hai, savings lifetime tak milti hai.' },
  { calculatorId: 'balance-transfer', sortOrder: 1, question: 'Balance Transfer ke liye minimum rate difference kitna hona chahiye?', answer: 'Generally 0.5% ya zyada rate difference par Balance Transfer beneficial hota hai, specially agar 5+ saal tenure baki ho. 0.25% difference par calculation carefully karo — processing fees savings ko eat kar sakti hain. BFS free mein calculation karke exact net saving batata hai.' },
  { calculatorId: 'balance-transfer', sortOrder: 2, question: 'Balance Transfer par koi foreclosure penalty hoti hai?', answer: 'RBI ke norms ke anusaar, floating rate home loans par koi foreclosure/prepayment penalty nahi hoti — chahe existing bank ho ya naya. Fixed rate loans par kuch banks 2-3% charge karte hain. Balance Transfer se pehle hamesha existing loan agreement check karo ya BFS se confirm karo.' },
  { calculatorId: 'balance-transfer', sortOrder: 3, question: 'Balance Transfer process mein kitna time lagta hai?', answer: 'BFS ke through average 7-15 working days: (1) New bank application (2-3 days), (2) Property verification (3-5 days), (3) NOC/Foreclosure letter existing bank se (3-7 days), (4) Disbursal (1-2 days). Hum poora process handle karte hain — aapko sirf documents dene hote hain.' },
  { calculatorId: 'balance-transfer', sortOrder: 4, question: 'Kya Balance Transfer ke saath Top-Up Loan bhi le sakte hain?', answer: 'Haan! Yeh ek major advantage hai. Balance Transfer ke saath naye bank se additional Top-Up amount (property value ka 70-80% minus outstanding) le sakte hain home loan rates (8.5-9%) par — jo Personal Loan rates (12-18%) se bahut sasta hai. Renovation, education, ya business ke liye best option.' },
  { calculatorId: 'balance-transfer', sortOrder: 5, question: 'Kitni baar Balance Transfer kar sakte hain?', answer: 'Technically unlimited baar, lekin practically har 1-2 saal se zyada frequent transfers se credit profile impact hota hai aur lenders suspicious ho jaate hain. Best strategy: Ek baar achhe rate par transfer karo aur phir prepayment strategy se loan jaldi close karo.' },

  // Prepayment
  { calculatorId: 'prepayment', sortOrder: 0, question: 'Loan prepayment se actually kitna faida hota hai?', answer: 'Example: Rs 50 Lakh loan, 20 saal, 9% rate. 5th saal mein Rs 5 Lakh lump sum prepayment karein toh tenure 4 saal 3 mahine ghatta hai + Total interest saving approximately Rs 9-10 Lakh. Prepayment ki power compounding ke against kaam karti hai — jitna pehle karo, utna zyada faida.' },
  { calculatorId: 'prepayment', sortOrder: 1, question: 'Prepayment karein ya mutual fund mein invest karein?', answer: 'Rule of thumb: Agar home loan rate > expected investment return toh prepay karo. Example: Loan rate 9.5% vs Equity MF expected 12% return toh invest karo. Loan rate 9.5% vs FD 7% toh prepay karo. Also consider 24(b) tax benefit — effective loan rate after tax = 9.5% x (1-0.30) = approx 6.65% at 30% slab.' },
  { calculatorId: 'prepayment', sortOrder: 2, question: 'Prepayment ke baad tenure ghatao ya EMI — kya better hai?', answer: 'Tenure ghataana financially better hai — aap total interest zyada bachate hain aur loan jaldi close hota hai. EMI ghatana better hai agar monthly cash flow tight hai. BFS suggestion: EMI stable rakho, prepayment se tenure ghataao, aur har saal bonus/windfall se part prepayment karo.' },
  { calculatorId: 'prepayment', sortOrder: 3, question: 'Kya floating rate loans par prepayment penalty hoti hai?', answer: 'RBI June 2012 ke circular ke baad, scheduled commercial banks floating rate home loans par koi prepayment penalty NAHI laga sakte — yeh legally banned hai. Fixed rate loans aur NBFCs par kuch cases mein 2-4% penalty lag sakti hai. Hamesha apna loan agreement check karo ya BFS se confirm karo.' },
  { calculatorId: 'prepayment', sortOrder: 4, question: 'Salary bonus milne par prepayment karni chahiye?', answer: 'Haan, absolutely karni chahiye. Annual bonus ya windfall income ka 50-80% home loan prepayment mein lagao. Yeh sabse tax-efficient aur high-return use hai agar aapka loan rate 8% se zyada hai. Remaining 20-50% emergency fund (3-6 months expenses) ya equity SIP mein rakho.' },
  { calculatorId: 'prepayment', sortOrder: 5, question: 'Part prepayment vs full foreclosure — kya better hai?', answer: 'Agar sufficient paisa available hai toh full foreclosure best hai — total interest savings maximum hoti hai aur loan ka burden hata jaata hai. Agar nahi toh regular part-prepayments (even Rs 10,000-20,000 monthly extra as prepayment) bhi dramatically tenure ghata dete hain. Consistency key hai — har saal karo.' },

  // Stamp Duty
  { calculatorId: 'stamp-duty', sortOrder: 0, question: 'Stamp Duty kya hoti hai aur kyun pay karni padti hai?', answer: 'Stamp Duty ek state government tax hai jo property purchase/transfer par lagta hai. Yeh property transaction ko legally register karne ke liye mandatory hai. Bina stamp duty aur registration ke property transfer legally valid nahi hoti — aap court mein enforce nahi kar sakte aur bank loan bhi iss property par nahi milega.' },
  { calculatorId: 'stamp-duty', sortOrder: 1, question: 'Different states mein stamp duty rate kitni hoti hai?', answer: 'Stamp Duty rates state-wise vary karti hain: Maharashtra 5-6%, Delhi 4-6%, UP 7%, Karnataka 5%, Rajasthan 5-6%. Mahila (female) buyer hone par many states 1-2% rebate dete hain — UP mein mahila buyer 6% instead of 7% pay karti hain. BFS calculator UP ke current rates use karta hai.' },
  { calculatorId: 'stamp-duty', sortOrder: 2, question: 'Stamp Duty ki calculation kaise hoti hai?', answer: 'Stamp Duty = MAX(Property Agreement Value, Circle Rate) x State Stamp Duty Rate. Registration Charges alag hote hain — typically 1% of property value (maximum Rs 30,000 in UP). Total cost = Stamp Duty + Registration Charge. Circle rate se neeche register karna illegal hai aur income tax notice aa sakta hai.' },
  { calculatorId: 'stamp-duty', sortOrder: 3, question: 'Kya Stamp Duty par income tax benefit milta hai?', answer: 'Haan! Section 80C ke under Stamp Duty aur Registration Charges paid for a new residential property deductible hain (within overall Rs 1.5 Lakh 80C limit). Sirf self-occupied residential property par applicable hai, commercial property ya plot par nahi. Registration same financial year mein hona zaroori hai.' },
  { calculatorId: 'stamp-duty', sortOrder: 4, question: 'Kya second hand/resale property par bhi same stamp duty lagti hai?', answer: 'Haan, resale property par bhi stamp duty aur registration charges usi rate par lagte hain — property value (ya circle rate, jo bhi zyada ho) ke basis par. Circle rate se kam price par register nahi kar sakte, warna income tax department ke under Section 56(2)(x) ka notice aa sakta hai.' },
  { calculatorId: 'stamp-duty', sortOrder: 5, question: 'Under-Construction property par stamp duty kab pay karni hoti hai?', answer: 'Under-construction property par stamp duty at time of Agreement for Sale signing lagti hai (not at final possession). Builder agreement value par calculate hoti hai. Ready-to-move properties par actual sale deed value ya circle rate (whichever higher) use hoti hai. BFS properly guide karta hai — kab aur kitna exactly pay karna hai.' }
];

async function main() {
  for (const faq of faqs) {
    await p.calculatorFAQ.create({ data: faq });
  }
  console.log('Successfully seeded', faqs.length, 'FAQs for 5 loan/tool calculators!');
}

main().catch(console.error).finally(() => p.$disconnect());
